export const MATERIA =[
    { value: 'Humanidades I', label: 'BA172 - Humanidades I' },
    { value: 'Deportes I', label: 'BU101 - Deportes I' },
    { value: 'Matemáticas 1', label: 'CB1B3 - Matemáticas 1' },
    { value: 'Programación I', label: 'IS105 - Programación I' },
    { value: 'Desarrollo del Pensamiento Lógico', label: 'IS142 - Desarrollo del Pensamiento Lógico' },
    { value: 'Introducción a la Informática', label: 'IS193 - Introducción a la Informática' },

    { value: 'Matemáticas 2', label: 'CB2A3 - Matemáticas 2' },
    { value: 'Álgebra Lineal', label: 'CB223 - Álgebra Lineal' },
    { value: 'Física I', label: 'CB234 - Física I' },
    { value: 'Laboratorio de Física I', label: 'CB242 - Laboratorio de Física I' },
    { value: 'Programación II', label: 'IS284 - Programación II' },

    { value: 'Humanidades II', label: 'BA372 - Humanidades II' },
    { value: 'Matemáticas 3', label: 'CB3A4 - Matemáticas 3' },
    { value: 'Física II', label: 'CB334 - Física II' },
    { value: 'Laboratorio de Física II', label: 'CB342 - Laboratorio de Física II' },
    { value: 'Estructura de Datos', label: 'IS304 - Estructura de Datos' },
    { value: 'Lógica', label: 'IS323 - Lógica' },

    { value: 'Matemáticas 4', label: 'CB4A4 - Matemáticas 4' },
    { value: 'Física III', label: 'CB434 - Física III' },
    { value: 'Laboratorio de Física III', label: 'CB442 - Laboratorio de Física III' },
    { value: 'Programación III', label: 'IS453 - Programación III' },
    { value: 'Fundamentos de Electrónica', label: 'IS474 - Fundamentos de Electrónica' },
    { value: 'Teoría de Sistemas', label: 'IS482 - Teoría de Sistemas' },
    { value: 'Laboratorio de Electrónica', label: 'IS543 - Laboratorio de Electrónica' },

    { value: 'Gramáticas y Lenguajes Formales', label: 'IS405 - Gramáticas y Lenguajes Formales' },
    { value: 'Administración de Empresas', label: 'IS503 - Administración de Empresas' },
    { value: 'Estadística', label: 'IS512 - Estadística' },
    { value: 'Programación IV', label: 'IS553 - Programación IV' },
    { value: 'Electrónica Digital', label: 'IS634 - Electrónica Digital' },
    { value: 'Laboratorio de Electrónica Digital', label: 'IS773 - Laboratorio de Electrónica Digital' },

    { value: 'Técnicas de la Comunicación', label: 'IS184 - Técnicas de la Comunicación' },
    { value: 'Arquitectura de Computadores', label: 'IS614 - Arquitectura de Computadores' },
    { value: 'Computación Gráfica', label: 'IS623 - Computación Gráfica' },
    { value: 'Base de Datos I', label: 'IS644 - Base de Datos I' },
    { value: 'Investigación de Operaciones', label: 'IS653 - Investigación de Operaciones' },
    { value: 'Estadística Especial', label: 'IS692 - Estadística Especial' },

    { value: 'Ingeniería de Software I', label: 'IS714 - Ingeniería de Software I' },
    { value: 'Comunicaciones I', label: 'IS723 - Comunicaciones I' },
    { value: 'Sistemas Operativos I', label: 'IS734 - Sistemas Operativos I' },
    { value: 'Compiladores', label: 'IS753 - Compiladores' },
    { value: 'Inteligencia Artificial', label: 'IS784 - Inteligencia Artificial' },

    { value: 'Gerencia de Proyectos', label: 'IS053 - Gerencia de Proyectos' },
    { value: 'Comunicaciones II', label: 'IS823 - Comunicaciones II' },
    { value: 'Legislación, Ética y Contratación', label: 'IS842 - Legislación, Ética y Contratación' },
    { value: 'Computación Blanda', label: 'IS845 - Computación Blanda' },
    { value: 'Ingeniería de Software II', label: 'IS884 - Ingeniería de Software II' },
    { value: 'Sistemas Distribuidos', label: 'IS893 - Sistemas Distribuidos' },

    { value: 'Laboratorio de Software', label: 'IS873 - Laboratorio de Software' },
    { value: 'Arquitectura Cliente Servidor', label: 'IS924 - Arquitectura Cliente Servidor' },
    { value: 'Administración de Proyectos de Software', label: 'IS953 - Administración de Proyectos de Software' },
    { value: 'Proyecto de Grado I', label: 'IS962 - Proyecto de Grado I' },
    { value: 'Ingeniería del Software III', label: 'IS9B3 - Ingeniería del Software III'},
    { value: 'HPC (High Performance Computing) I', label: 'IS9D3 - HPC (High Performance Computing) I' },
    { value: 'Comunicaciones III', label: 'IS923 - Comunicaciones III' },

    { value: 'Auditoría de Sistemas', label: 'IS023 - Auditoría de Sistemas' },
    { value: 'Constitución Política', label: 'IS031 - Constitución Política' },
    { value: 'Emprendimiento', label: 'IS073 - Emprendimiento' },
    { value: 'Planeación Estratégica de Sistemas', label: 'IS042 - Planeación Estratégica de Sistemas' },
    { value: 'Administración de Sistemas de Información', label: 'IS013 - Administración de Sistemas de Información' },
]