export const MATERIA = [
    { value: 'HPC (High Performance Computing) I', label: 'IS9D3 - HPC (High Performance Computing) I', id: 'IS9D3' },
    { value: 'Humanidades I', label: 'BA172 - Humanidades I', id: 'BA172' },
    { value: 'Deportes I', label: 'BU101 - Deportes I', id: 'BU101' },
    { value: 'Matemáticas 1', label: 'CB1B3 - Matemáticas 1', id: 'CB1B3' },
    { value: 'Programación I', label: 'IS105 - Programación I', id: 'IS105' },
    { value: 'Desarrollo del Pensamiento Lógico', label: 'IS142 - Desarrollo del Pensamiento Lógico', id: 'IS142' },
    { value: 'Introducción a la Informática', label: 'IS193 - Introducción a la Informática', id: 'IS193' },

    { value: 'Matemáticas 2', label: 'CB2A3 - Matemáticas 2', id: 'CB2A3' },
    { value: 'Álgebra Lineal', label: 'CB223 - Álgebra Lineal', id: 'CB223' },
    { value: 'Física I', label: 'CB234 - Física I', id: 'CB234' },
    { value: 'Laboratorio de Física I', label: 'CB242 - Laboratorio de Física I', id: 'CB242' },
    { value: 'Programación II', label: 'IS284 - Programación II', id: 'IS284' },

    { value: 'Humanidades II', label: 'BA372 - Humanidades II', id: 'BA372' },
    { value: 'Matemáticas 3', label: 'CB3A4 - Matemáticas 3', id: 'CB3A4' },
    { value: 'Física II', label: 'CB334 - Física II', id: 'CB334' },
    { value: 'Laboratorio de Física II', label: 'CB342 - Laboratorio de Física II', id: 'CB342' },
    { value: 'Estructura de Datos', label: 'IS304 - Estructura de Datos', id: 'IS304' },
    { value: 'Lógica', label: 'IS323 - Lógica', id: 'IS323' },

    { value: 'Matemáticas 4', label: 'CB4A4 - Matemáticas 4', id: 'CB4A4' },
    { value: 'Física III', label: 'CB434 - Física III', id: 'CB434' },
    { value: 'Laboratorio de Física III', label: 'CB442 - Laboratorio de Física III', id: 'CB442' },
    { value: 'Programación III', label: 'IS453 - Programación III', id: 'IS453' },
    { value: 'Fundamentos de Electrónica', label: 'IS474 - Fundamentos de Electrónica', id: 'IS474' },
    { value: 'Teoría de Sistemas', label: 'IS482 - Teoría de Sistemas', id: 'IS482' },
    { value: 'Laboratorio de Electrónica', label: 'IS543 - Laboratorio de Electrónica', id: 'IS543' },

    { value: 'Gramáticas y Lenguajes Formales', label: 'IS405 - Gramáticas y Lenguajes Formales', id: 'IS405' },
    { value: 'Administración de Empresas', label: 'IS503 - Administración de Empresas', id: 'IS503' },
    { value: 'Estadística', label: 'IS512 - Estadística', id: 'IS512' },
    { value: 'Programación IV', label: 'IS553 - Programación IV', id: 'IS553' },
    { value: 'Electrónica Digital', label: 'IS634 - Electrónica Digital', id: 'IS634' },
    { value: 'Laboratorio de Electrónica Digital', label: 'IS773 - Laboratorio de Electrónica Digital', id: 'IS773' },

    { value: 'Técnicas de la Comunicación', label: 'IS184 - Técnicas de la Comunicación', id: 'IS184' },
    { value: 'Arquitectura de Computadores', label: 'IS614 - Arquitectura de Computadores', id: 'IS614' },
    { value: 'Computación Gráfica', label: 'IS623 - Computación Gráfica', id: 'IS623' },
    { value: 'Base de Datos I', label: 'IS644 - Base de Datos I', id: 'IS644' },
    { value: 'Investigación de Operaciones', label: 'IS653 - Investigación de Operaciones', id: 'IS653' },
    { value: 'Estadística Especial', label: 'IS692 - Estadística Especial', id: 'IS692' },

    { value: 'Ingeniería de Software I', label: 'IS714 - Ingeniería de Software I', id: 'IS714' },
    { value: 'Comunicaciones I', label: 'IS723 - Comunicaciones I', id: 'IS723' },
    { value: 'Sistemas Operativos I', label: 'IS734 - Sistemas Operativos I', id: 'IS734' },
    { value: 'Compiladores', label: 'IS753 - Compiladores', id: 'IS753' },
    { value: 'Inteligencia Artificial', label: 'IS784 - Inteligencia Artificial', id: 'IS784' },

    { value: 'Gerencia de Proyectos', label: 'IS053 - Gerencia de Proyectos', id: 'IS053' },
    { value: 'Comunicaciones II', label: 'IS823 - Comunicaciones II', id: 'IS823' },
    { value: 'Legislación, Ética y Contratación', label: 'IS842 - Legislación, Ética y Contratación', id: 'IS842' },
    { value: 'Computación Blanda', label: 'IS845 - Computación Blanda', id: 'IS845' },
    { value: 'Ingeniería de Software II', label: 'IS884 - Ingeniería de Software II', id: 'IS884' },
    { value: 'Sistemas Distribuidos', label: 'IS893 - Sistemas Distribuidos', id: 'IS893' },

    { value: 'Laboratorio de Software', label: 'IS873 - Laboratorio de Software', id: 'IS873' },
    { value: 'Arquitectura Cliente Servidor', label: 'IS924 - Arquitectura Cliente Servidor', id: 'IS924' },
    { value: 'Administración de Proyectos de Software', label: 'IS953 - Administración de Proyectos de Software', id: 'IS953' },
    { value: 'Proyecto de Grado I', label: 'IS962 - Proyecto de Grado I', id: 'IS962' },
    { value: 'Ingeniería del Software III', label: 'IS9B3 - Ingeniería del Software III', id: 'IS9B3' },
    { value: 'HPC (High Performance Computing) I', label: 'IS9D3 - HPC (High Performance Computing) I', id: 'IS9D3' },
    { value: 'Comunicaciones III', label: 'IS923 - Comunicaciones III', id: 'IS923' },

    { value: 'Auditoría de Sistemas', label: 'IS023 - Auditoría de Sistemas', id: 'IS023' },
    { value: 'Constitución Política', label: 'IS031 - Constitución Política', id: 'IS031' },
    { value: 'Emprendimiento', label: 'IS073 - Emprendimiento', id: 'IS073' },
    { value: 'Planeación Estratégica de Sistemas', label: 'IS042 - Planeación Estratégica de Sistemas', id: 'IS042' },
    { value: 'Administración de Sistemas de Información', label: 'IS013 - Administración de Sistemas de Información', id: 'IS013' },
];
